spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/aggpay?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 30000

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
    password: ${REDIS_PASSWORD:}

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}
  producer:
    group: pay-service-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2

wanli:
  sign:
    check: 0

telegram-bot:
  enabled: true
  token: ${TELEGRAM_BOT_TOKEN:}


shopline:
  app-key: ${SHOPLINE_APP_KEY:a3b199b51b1dbf5eec4b73ae53cdef1561b8eefb}
  app-secret: ${SHOPLINE_APP_SECRET:e70f73b4ab5fc302e23e7ffbcb0af54cfdf0266f}
  public-key: ${SHOPLINE_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2zkSKtgm8UJwLs7T80DF2i3hmeysbIUJQHAvKF/mbBJWibwa1rrdDvS6gHzNwC5M0ndLsLkq8n75PeFHHZy3ahhLPLs19y07RMRArvvUO0aLPR1GW5Ef21BpYJ2nWcjKPitsv37qS3CpqzgV198ZGTApTPZ36dmhO6eNGewa1CnXquLkkw3T18OoFYnE1QQ2dEqflkzfUFUKn3id8L+G7j0511kdHULUFerA+CD8SYYXnrB9cQaRBT7dJB2Y0rYXh7v0Uw+0NnuDjs5Zt95iaJTfFCT4Et74/b9h1MgA+kauHkYGo3mgvOAkCHf0NF7/C1nMbM22Ru5bQBG7g7ZjlwIDAQAB}
  responsePrivateKey: ${SHOPLINE_RESPONSE_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDO/TD8axRYRHG+OE6WIFuHH6tyovmqVBw0J5omnvp3RiK1iCnzoJ7M11mK+a0xCshZst1gtMTI+KDPC2OYJMOjckAKSSZtM0FEm2Saq9ZyCWvJady2YsFQgaHtpsJA1YGe18f7sxsn5aCfdsQZ5Zr21OOzSD/yhS9gbIgDYQg0lTtW8w/Q6kdJgRLJfb4i01gKCseBk0v+YRDSb3FCKL0jcWMvdRVySCSXH2CC20udYNOhFSHpbfbu4zGmCAAQKhKVanFJWJYxoE3YKIKIZZ0/BqXIdY4zBQvnKY71cE35/IXDcqdlPLw6uLVzmHbe6ESWmFqc8K4UbebP6AZslvVDAgMBAAECggEARChDFRr9XANNoOFRn0WQXfIjtl/L7jY8A0B3FfiLaPMDQttPVRWytKjEp2qHiPqP9llbZBiiI7sa2JJbfSG9+fgI9loX+SVDfJ/ehL/IoUxQ3cWqE7R5C1VkSKj8lfS39eH/y/WyH3URavDkqdJdMKHxSHul8unAK/QQ5WvyE73oZos8AWRa9VWKiXnw/kJrBFfazsxvqXSWE3pNGHP4MJfuxYHGKY2bC9Z8FVKdK5h71vW1q+TPPGTZAcAoZztR/VbB34SiUaUK5NwLiRT7zXY92f8LeUF0ChizO5gZGypkhwoODdCuR4Htw7otap2eBWnFl5tfLAfUicoV/GLLgQKBgQDrDMJ/JfGol5C2OOk2RfiEiG9aWkvF+Rr3DRIPC1i5KuZcCXpZjTgn6xZDvbRkry5hcXjjy3lzOlP2hzfbF1Gyaw1LtiWEB5x3Zvu9ddKlavdUIotv+1F3ekCP1QnQiIpGq4s/qQ6PLtnrkq8e+pT+s+jX+LpJw/xmLNwYezzaUQKBgQDhcCe1e5AgvTn1y/vNkPyw+fUGS35lQblRbj1Y4YelA5kImi5pkx3iFQb6XsR1Wmn4hv9QRZhTq5cXW9JZXZZzhI9cEdFAfz7EDkyClHE4PP96dBR5gqniZLE5ubk8oiMmEcytWQWmwb+xX7/nnNPby7i6SRguCXfOiGUwJ9EdUwKBgHqDERFSxq2YKk5ARZYLTGhP8LJIZDxRBbQFNQdwY5NH//+y1Pm+OKndx6IRS+g6wtL5YQhicvATU9YoTn28ntF/KNPwoYc6rFwz6jyrH9smcLmCs+jvNlwu9V3CrbXqpSAGo7LPvA33XpCByRM9itFjFpcTRo3SQElFUobUHTixAoGAKSCA3gbwwEhFLqZMBbCRqOew37keEfLvj/+AiZp7WItTe9JE7VW9eeVEJKDtTkt0UbavFUHdDEadhdFmio8cR27DiJRnjFCqbrH9G0VhclUOdpR+t7wyqe6ctl8/f+REbUmKAYXgFg/6nK1PIT3nGI4N4U48bwmjJbaUXzikWakCgYEAsmUH21UvEZ6I6xS84U/0kol0s/wVN36skItocI00lW2X+4T+9xunvAx3xXzN2vTZ7PzYr6KV9TH7BNSG53L3x8QEqDOokE2uVNEOOs/gYFZTkavmNT5hkIZsdOj2C40bcnh1vJrZk9lf3G12B+MfVULl4RVw/XM/2Hcjrs66AeI=}
  1api-base: https://openapi.myshopline.com
  api-version: 2023-01
  redirect-uri: ${SHOPLINE_REDIRECT_URI:https://pay.zyapay.com/api/pay/shopline/callback}
  login-base-url: ${SHOPLINE_LOGIN_BASE_URL:https://13.234.6.115}
  scopes: write_discounts,write_store_information,read_store_information,write_payment_gateways,read_script_tags,write_shop_policy,write_price_rules,write_fulfillment_service,read_bulkoperation,write_inventory,read_orders,write_content,read_marketing_event,read_inventory,write_orders,read_discounts,read_products,read_content,read_returns,read_fulfillment_service,write_products,read_location,read_shipping,read_translation,read_selling_plan_group,read_themes,write_subscription_contracts,write_bulkoperation,write_translation,read_customers,read_payment,write_checkouts,read_shop_policy,write_customers,read_markets,read_product_listings,write_files,read_store_metrics,read_gift_card,write_script_tags,write_product_listings,write_return,write_page,read_subscription_contracts,write_selling_plan_group,read_assigned_fulfillment_orders,write_shipping,read_page,write_themes,read_price_rules,write_gift_card,write_markets,write_assigned_fulfillment_orders,read_files,read_draft_orders,write_marketing_event,write_draft_orders

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
